# Build stage
FROM golang:1.23.0 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
# Compile the Worker statically
RUN CGO_ENABLED=0 GOOS=linux go build -o /fleet-worker ./cmd/worker/main.go

# Final stage
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /fleet-worker .
CMD ["./fleet-worker"]